name: release-build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
      run: ./gradlew -PprojVersion="${{ github.event.release.tag_name }}" build
      - name: Upload jvm
      id: upload-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/libs/7dtd-rgw-map-image-builder.jar
        asset_name: 7dtd-rgw-map-image-builder.jar
        asset_label: jar
        asset_content_type: application/octet-stream